default:
  image: node:latest

stages:
  - test
  - release
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

test:lint:
  stage: test
  script:
    - yarn install
    - yarn lint
  except:
    - tags

test:jest:
  stage: test
  script:
    - yarn install
    - yarn test
  except:
    - tags


publish:
  stage: release
  cache:
    policy: pull
  script:
    - yarn install
    - yarn build
    - yarn release
  only:
    refs:
      - master

pages:
  stage: deploy
  cache:
    policy: pull
  script:
    - yarn install
    - yarn build:typedoc
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
